Fix problem with JSON encoding when creating repositories
Now using a TMemoryStream instead of a TStringStream.

The GitBucket server was giving this error:
17:16:09.070 [qtp1826771953-15] ERROR g.core.controller.ApiController - Catch unhandled error in request: Request(POST //127.0.0.1:8080/api/v3/user/repos)@5e51d821
com.fasterxml.jackson.databind.JsonMappingException: No content to map due to end-of-input
 at [Source: ; line: 1, column: 0]